// <auto-generated />
using EPareH60Store.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EPareH60Store.Migrations
{
    [DbContext(typeof(H60assignmentDbEpContext))]
    [Migration("20260923000000_InitialAssignmentEntities")]
    partial class InitialAssignmentEntities
    {
    }
}
