// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using EPareH60Store.Models;

namespace EPareH60Store.Migrations
{
    [DbContext(typeof(H60assignmentDbEpContext))]
    partial class InitialAssignmentEntities
    {
    }
}
